# Author: Edoardo Sabatini
# @26/10/2020
# ######################## 
#
version: '3'
services:
  redis-server:
    image: 'redis'
  node-server:
    build: ./invinoveritas-node
    volumes:
      - ./invinoveritas-node:/app/invinoveritas-node
    ports:
      - "4001:8081"
    container_name: node-api
  react-ui:
    build:
      context: ./invinoveritas-react
    ports:
      - "8080:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./invinoveritas-react:/usr/src/app/invinoveritas-react
       - /usr/src/app/invinoveritas-react/node_modules
